def menu():
    print("-"*70)
    print("\tBanking Information System")
    print("-"*70)
    print("\t1. Add New Customer(Opening An Account)")
    print("\t2. Delete Customer(Closing An Account)")
    print("\t3. WithDraw")
    print("\t4. Deposit")
    print("\t5. View Customer Details")
    print("\t6. View All Customers Details")
    print("\t7. Search Customer")
    print("\t8. Pin Generate")
    print("\t9. Pin Update")
    print("\t10. Exit")
    print("-"*70)